"""Generate the immutable PET v1 catalog artifact and migration 007.

The input is the user-provided 20-domain, 500-title specification.  Generation
is deterministic: source newlines are normalized and JSON keys are sorted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOMAIN = re.compile(r"^(\d{1,2})\.\s+(.+)$")
FEATURE_ID = "PET-{domain:02d}-{item:02d}"

OWNERS = {
    1: "executive-pet", 2: "executive-pet", 3: "customer-pet", 4: "development-pet",
    5: "development-pet", 6: "creative-pet", 7: "finance-pet", 8: "research-pet",
    9: "creative-pet", 10: "creative-pet", 11: "development-pet", 12: "customer-pet",
    13: "sales-pet", 14: "fulfillment-pet", 15: "finance-pet", 16: "marketing-pet",
    17: "security-pet", 18: "quality-pet", 19: "development-pet", 20: "executive-pet",
}


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def parse_source(text: str) -> list[dict[str, object]]:
    lines = [line.strip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    start = lines.index("1. Core Identity and Personality")
    stop = lines.index("Advanced PET Role Ideas")
    features: list[dict[str, object]] = []
    domain = 0
    item = 0
    for line in lines[start:stop]:
        if not line:
            continue
        match = DOMAIN.match(line)
        if match:
            next_domain = int(match.group(1))
            if next_domain != domain + 1:
                raise ValueError(f"Expected domain {domain + 1}, got {next_domain}")
            if domain and item != 25:
                raise ValueError(f"Domain {domain} has {item} titles, expected 25")
            domain = next_domain
            item = 0
            continue
        if not domain:
            continue
        item += 1
        features.append(
            {
                "feature_id": FEATURE_ID.format(domain=domain, item=item),
                "domain_no": domain,
                "item_no": item,
                "source_order": (domain - 1) * 25 + item,
                "source_title": line,
                "sensitivity": "high" if domain == 17 else "elevated" if domain in {12, 14, 15, 18} else "standard",
                "default_owner_pet_id": OWNERS[domain],
            }
        )
    if domain != 20 or item != 25 or len(features) != 500:
        raise ValueError(f"Expected 20 domains x 25 titles, got domain={domain}, item={item}, total={len(features)}")
    ids = {row["feature_id"] for row in features}
    titles = {(row["domain_no"], row["item_no"]) for row in features}
    if len(ids) != 500 or len(titles) != 500:
        raise ValueError("Catalog IDs or domain/item pairs are not unique")
    return features


def build_artifact(source_text: str) -> dict[str, object]:
    normalized_source = source_text.replace("\r\n", "\n").replace("\r", "\n")
    features = parse_source(normalized_source)
    catalog_sha256 = hashlib.sha256(canonical_json(features).encode("utf-8")).hexdigest()
    source_sha256 = hashlib.sha256(normalized_source.encode("utf-8")).hexdigest()
    for row in features:
        contract = {
            "feature_id": row["feature_id"],
            "source_title": row["source_title"],
            "domain_no": row["domain_no"],
            "item_no": row["item_no"],
            "execution_state": "planned",
        }
        version_content = {
            "contract": contract,
            "acceptance_schema": {"type": "object", "required": ["evidence"], "properties": {"evidence": {"type": "array", "minItems": 1}}},
            "permissions": {"mode": "least_privilege", "grants": []},
            "failure_modes": {"on_failure": "remain_planned", "requires_human_review": row["sensitivity"] != "standard"},
        }
        row["version"] = 1
        row["content_sha256"] = hashlib.sha256(canonical_json(version_content).encode("utf-8")).hexdigest()
        row.update(version_content)
    return {
        "schema_version": 1,
        "catalog_id": "pet-feature-catalog-v1",
        "expected_total": 500,
        "source_sha256": source_sha256,
        "catalog_sha256": catalog_sha256,
        "features": features,
    }


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_migration(artifact: dict[str, object]) -> str:
    payload = canonical_json(artifact["features"])
    source_hash = artifact["source_sha256"]
    catalog_hash = artifact["catalog_sha256"]
    return f"""-- Generated by scripts/generate_pet_feature_catalog.py; do not hand-edit.
-- Source SHA-256: {source_hash}
-- Catalog SHA-256: {catalog_hash}

create table if not exists pet_feature_catalog_sources (
    catalog_id text primary key,
    schema_version integer not null check (schema_version > 0),
    expected_total integer not null check (expected_total = 500),
    source_sha256 char(64) not null check (source_sha256 ~ '^[0-9a-f]{{64}}$'),
    catalog_sha256 char(64) not null check (catalog_sha256 ~ '^[0-9a-f]{{64}}$'),
    created_at timestamptz not null default now()
);

create table if not exists pet_feature_definitions (
    feature_id text primary key check (feature_id ~ '^PET-(0[1-9]|1[0-9]|20)-(0[1-9]|1[0-9]|2[0-5])$'),
    domain_no smallint not null check (domain_no between 1 and 20),
    item_no smallint not null check (item_no between 1 and 25),
    source_title text not null check (btrim(source_title) <> ''),
    source_order smallint not null unique check (source_order between 1 and 500),
    sensitivity text not null check (sensitivity in ('standard', 'elevated', 'high')),
    default_owner_pet_id text,
    created_at timestamptz not null default now(),
    retired_at timestamptz,
    unique (domain_no, item_no),
    check (feature_id = format('PET-%s-%s', lpad(domain_no::text, 2, '0'), lpad(item_no::text, 2, '0'))),
    check (source_order = ((domain_no - 1) * 25 + item_no))
);

create table if not exists pet_feature_versions (
    id bigserial primary key,
    feature_id text not null references pet_feature_definitions(feature_id) on delete restrict,
    version integer not null check (version > 0),
    contract jsonb not null check (jsonb_typeof(contract) = 'object'),
    acceptance_schema jsonb not null check (jsonb_typeof(acceptance_schema) = 'object'),
    permissions jsonb not null check (jsonb_typeof(permissions) = 'object'),
    failure_modes jsonb not null check (jsonb_typeof(failure_modes) = 'object'),
    content_sha256 char(64) not null check (content_sha256 ~ '^[0-9a-f]{{64}}$'),
    created_by text not null check (btrim(created_by) <> ''),
    created_at timestamptz not null default now(),
    supersedes_version integer,
    unique (feature_id, version),
    unique (feature_id, content_sha256),
    foreign key (feature_id, supersedes_version) references pet_feature_versions(feature_id, version) on delete restrict,
    check (supersedes_version is null or supersedes_version < version)
);

create table if not exists pet_feature_state_current (
    feature_id text primary key,
    feature_version integer not null,
    state char(1) not null check (state in ('P', 'G', 'O', 'R')),
    release_id bigint,
    last_verified_at timestamptz,
    verification_expires_at timestamptz,
    row_version bigint not null default 1 check (row_version > 0),
    updated_at timestamptz not null default now(),
    foreign key (feature_id, feature_version) references pet_feature_versions(feature_id, version) on delete restrict,
    check (verification_expires_at is null or last_verified_at is not null),
    check (verification_expires_at is null or verification_expires_at > last_verified_at)
);

create table if not exists pet_feature_state_events (
    id bigserial primary key,
    feature_id text not null,
    feature_version integer not null,
    from_state char(1) check (from_state is null or from_state in ('P', 'G', 'O', 'R')),
    to_state char(1) not null check (to_state in ('P', 'G', 'O', 'R')),
    release_id bigint,
    actor text not null check (btrim(actor) <> ''),
    reason text not null check (btrim(reason) <> ''),
    idempotency_key text not null unique check (btrim(idempotency_key) <> ''),
    created_at timestamptz not null default now(),
    foreign key (feature_id, feature_version) references pet_feature_versions(feature_id, version) on delete restrict
);

create index if not exists idx_pet_feature_state_state_updated
    on pet_feature_state_current(state, updated_at desc);
create index if not exists idx_pet_feature_state_verification_expiry
    on pet_feature_state_current(verification_expires_at)
    where verification_expires_at is not null;
create index if not exists idx_pet_feature_definitions_owner_domain
    on pet_feature_definitions(default_owner_pet_id, domain_no, source_order);
create index if not exists idx_pet_feature_state_events_feature_time
    on pet_feature_state_events(feature_id, created_at desc, id desc);

create or replace function reject_pet_feature_immutable_mutation()
returns trigger language plpgsql as $$
begin
    raise exception '% is append-only/immutable', tg_table_name;
end;
$$;

drop trigger if exists trg_pet_feature_definitions_immutable on pet_feature_definitions;
create trigger trg_pet_feature_definitions_immutable before update or delete on pet_feature_definitions
for each row execute function reject_pet_feature_immutable_mutation();
drop trigger if exists trg_pet_feature_versions_immutable on pet_feature_versions;
create trigger trg_pet_feature_versions_immutable before update or delete on pet_feature_versions
for each row execute function reject_pet_feature_immutable_mutation();
drop trigger if exists trg_pet_feature_events_immutable on pet_feature_state_events;
create trigger trg_pet_feature_events_immutable before update or delete on pet_feature_state_events
for each row execute function reject_pet_feature_immutable_mutation();
drop trigger if exists trg_pet_feature_catalog_sources_immutable on pet_feature_catalog_sources;
create trigger trg_pet_feature_catalog_sources_immutable before update or delete on pet_feature_catalog_sources
for each row execute function reject_pet_feature_immutable_mutation();

create or replace function guard_pet_feature_current_mutation()
returns trigger language plpgsql as $$
begin
    if current_setting('aiops.pet_state_transition', true) is distinct from 'allowed' then
        raise exception 'pet_feature_state_current may only change through transition_pet_feature_state';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_pet_feature_current_guard on pet_feature_state_current;
create trigger trg_pet_feature_current_guard before update or delete on pet_feature_state_current
for each row execute function guard_pet_feature_current_mutation();

create or replace function seed_pet_feature_catalog_v1()
returns table(inserted_definitions bigint, inserted_versions bigint, inserted_states bigint, inserted_events bigint)
language plpgsql as $seed$
declare
    catalog jsonb := $catalog${payload}$catalog$::jsonb;
    affected bigint;
begin
    insert into pet_feature_catalog_sources(catalog_id, schema_version, expected_total, source_sha256, catalog_sha256)
    values ('pet-feature-catalog-v1', 1, 500, {sql_literal(str(source_hash))}, {sql_literal(str(catalog_hash))})
    on conflict (catalog_id) do nothing;

    if not exists (
        select 1 from pet_feature_catalog_sources
        where catalog_id = 'pet-feature-catalog-v1' and schema_version = 1 and expected_total = 500
          and source_sha256 = {sql_literal(str(source_hash))} and catalog_sha256 = {sql_literal(str(catalog_hash))}
    ) then
        raise exception 'PET catalog source/hash mismatch';
    end if;

    insert into pet_feature_definitions(feature_id, domain_no, item_no, source_title, source_order, sensitivity, default_owner_pet_id)
    select e->>'feature_id', (e->>'domain_no')::smallint, (e->>'item_no')::smallint,
           e->>'source_title', (e->>'source_order')::smallint, e->>'sensitivity', e->>'default_owner_pet_id'
    from jsonb_array_elements(catalog) e
    on conflict (feature_id) do nothing;
    get diagnostics inserted_definitions = row_count;

    if exists (
        select 1 from jsonb_array_elements(catalog) e
        left join pet_feature_definitions d on d.feature_id = e->>'feature_id'
        where d.feature_id is null or d.domain_no <> (e->>'domain_no')::smallint
           or d.item_no <> (e->>'item_no')::smallint or d.source_title <> e->>'source_title'
           or d.source_order <> (e->>'source_order')::smallint or d.sensitivity <> e->>'sensitivity'
           or d.default_owner_pet_id is distinct from e->>'default_owner_pet_id'
    ) then
        raise exception 'PET catalog definition mismatch; immutable source was altered';
    end if;

    insert into pet_feature_versions(feature_id, version, contract, acceptance_schema, permissions, failure_modes,
                                     content_sha256, created_by, supersedes_version)
    select e->>'feature_id', 1, e->'contract', e->'acceptance_schema', e->'permissions', e->'failure_modes',
           e->>'content_sha256', 'pet-feature-catalog-v1', null
    from jsonb_array_elements(catalog) e
    on conflict (feature_id, version) do nothing;
    get diagnostics inserted_versions = row_count;

    if exists (
        select 1 from jsonb_array_elements(catalog) e
        left join pet_feature_versions v on v.feature_id = e->>'feature_id' and v.version = 1
        where v.id is null or v.contract <> e->'contract' or v.acceptance_schema <> e->'acceptance_schema'
           or v.permissions <> e->'permissions' or v.failure_modes <> e->'failure_modes'
           or v.content_sha256 <> e->>'content_sha256' or v.created_by <> 'pet-feature-catalog-v1'
    ) then
        raise exception 'PET catalog version mismatch; immutable contract was altered';
    end if;

    insert into pet_feature_state_current(feature_id, feature_version, state, row_version)
    select e->>'feature_id', 1, 'P', 1 from jsonb_array_elements(catalog) e
    on conflict (feature_id) do nothing;
    get diagnostics inserted_states = row_count;

    if exists (
        select 1 from jsonb_array_elements(catalog) e
        left join pet_feature_state_current s on s.feature_id = e->>'feature_id'
        where s.feature_id is null or s.feature_version <> 1
    ) then
        raise exception 'PET catalog current-state coverage mismatch';
    end if;

    insert into pet_feature_state_events(feature_id, feature_version, from_state, to_state, actor, reason, idempotency_key)
    select e->>'feature_id', 1, null, 'P', 'pet-feature-catalog-v1', 'Initial catalog state',
           'pet-feature-catalog-v1:' || (e->>'feature_id') || ':initial'
    from jsonb_array_elements(catalog) e
    on conflict (idempotency_key) do nothing;
    get diagnostics inserted_events = row_count;

    if (select count(*) from pet_feature_definitions) <> 500
       or (select count(*) from pet_feature_versions where version = 1) <> 500
       or (select count(*) from pet_feature_state_current) <> 500
       or (select count(*) from pet_feature_state_events where actor = 'pet-feature-catalog-v1') <> 500 then
        raise exception 'PET catalog integrity failure: expected exactly 500 definitions, v1 versions, current states, and initial events';
    end if;
    return next;
end;
$seed$;

create or replace function transition_pet_feature_state(
    p_feature_id text,
    p_expected_row_version bigint,
    p_to_state char(1),
    p_actor text,
    p_reason text,
    p_idempotency_key text,
    p_release_id bigint default null,
    p_last_verified_at timestamptz default null,
    p_verification_expires_at timestamptz default null
)
returns pet_feature_state_current language plpgsql as $$
declare
    current_row pet_feature_state_current%rowtype;
    existing_event pet_feature_state_events%rowtype;
begin
    if p_to_state not in ('P', 'G', 'O', 'R') or btrim(coalesce(p_actor, '')) = ''
       or btrim(coalesce(p_reason, '')) = '' or btrim(coalesce(p_idempotency_key, '')) = '' then
        raise exception 'Invalid PET feature transition input';
    end if;
    select * into existing_event from pet_feature_state_events where idempotency_key = p_idempotency_key;
    if found then
        if existing_event.feature_id <> p_feature_id or existing_event.to_state <> p_to_state
           or existing_event.actor <> p_actor or existing_event.reason <> p_reason
           or existing_event.release_id is distinct from p_release_id then
            raise exception 'PET transition idempotency key reused with different content';
        end if;
        select * into current_row from pet_feature_state_current where feature_id = p_feature_id;
        return current_row;
    end if;

    select * into current_row from pet_feature_state_current where feature_id = p_feature_id for update;
    if not found then raise exception 'Unknown PET feature %', p_feature_id; end if;
    if current_row.row_version <> p_expected_row_version then
        raise exception 'PET feature row version conflict: expected %, actual %', p_expected_row_version, current_row.row_version;
    end if;
    if p_to_state = 'O' and (p_release_id is null or p_last_verified_at is null) then
        raise exception 'Operational promotion requires release_id and verification timestamp';
    end if;

    insert into pet_feature_state_events(feature_id, feature_version, from_state, to_state, release_id, actor, reason, idempotency_key)
    values (current_row.feature_id, current_row.feature_version, current_row.state, p_to_state,
            p_release_id, p_actor, p_reason, p_idempotency_key);
    perform set_config('aiops.pet_state_transition', 'allowed', true);
    update pet_feature_state_current
       set state = p_to_state, release_id = p_release_id, last_verified_at = p_last_verified_at,
           verification_expires_at = p_verification_expires_at, row_version = row_version + 1, updated_at = now()
     where feature_id = p_feature_id returning * into current_row;
    return current_row;
end;
$$;

create or replace view pet_feature_state_summary as
select count(*) filter (where state = 'O')::integer as operational,
       count(*) filter (where state = 'G')::integer as gated,
       count(*) filter (where state = 'P')::integer as planned,
       count(*) filter (where state = 'R')::integer as rejected,
       count(*)::integer as total,
       500::integer as expected_total,
       (count(*) = 500)::boolean as integrity
from pet_feature_state_current;

select * from seed_pet_feature_catalog_v1();
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--artifact", type=Path, default=ROOT / "config" / "pet_feature_catalog_v1.json")
    parser.add_argument("--migration", type=Path, default=ROOT / "sql" / "migrations" / "007_pet_feature_catalog.sql")
    args = parser.parse_args()
    artifact = build_artifact(args.source.read_text(encoding="utf-8"))
    args.artifact.parent.mkdir(parents=True, exist_ok=True)
    args.artifact.write_text(json.dumps(artifact, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    args.migration.parent.mkdir(parents=True, exist_ok=True)
    args.migration.write_text(build_migration(artifact), encoding="utf-8", newline="\n")
    print(f"generated {len(artifact['features'])} features: {args.artifact} and {args.migration}")


if __name__ == "__main__":
    main()
